/*---------------------------------------------------------------------------------------------
 *  Loads the dance bundle into the workbench's main thread.
 *
 *  The dance source is shipped as `out/web-extension.js` — a CommonJS bundle produced
 *  by esbuild. We embed it as a string literal at build time (see
 *  install-into-vscode.sh, which writes danceBundle.ts) and `new Function`-eval
 *  it here with a synthetic `require("vscode")` that hands back our shim.
 *
 *  Net effect: dance's `activate(ctx)` runs as part of the workbench startup,
 *  and every `vscode.*` call is a direct synchronous-or-promise function call
 *  on a workbench service. No worker boundary, no websocket, no IPC.
 *--------------------------------------------------------------------------------------------*/

import { Disposable, DisposableStore } from '../../../../base/common/lifecycle.js';
import { URI } from '../../../../base/common/uri.js';
import { ILogService } from '../../../../platform/log/common/log.js';
import { IVscodeShim } from './vscodeShim.js';
// danceBundle.ts is generated by dance/install-into-vscode.sh just before the workbench compile.
// It exports two strings: the JS bundle and the manifest JSON.
import { DANCE_BUNDLE_JS, DANCE_MANIFEST_JSON } from './danceBundle.js';

export class DanceMainThreadLoader extends Disposable {
	private _exports?: { activate?: (ctx: any) => Promise<any> | any; deactivate?: () => unknown; api?: any };
	private _activated = false;

	constructor(
		// `shim` must have been created synchronously inside an instantiationService.invokeFunction
		// callback by the caller — ServicesAccessor is only valid for that one synchronous frame.
		private readonly shim: IVscodeShim,
		// ownDisposables is the same store the shim was created in; the caller already
		// registered it for disposal alongside the workbench contribution, so we don't
		// double-register here.
		private readonly ownDisposables: DisposableStore,
		private readonly logService: ILogService,
	) {
		super();
	}

	async activate(): Promise<void> {
		if (this._activated) { return; }
		this._activated = true;

		// Surface progress via console.* too, because logService output goes through
		// the workbench's logger pipeline which doesn't always reach the browser
		// devtools console when something goes wrong early.
		// eslint-disable-next-line no-console
		console.info('[dance] loader.activate(): bundle len=' + (DANCE_BUNDLE_JS?.length ?? 0));

		let manifest: any = {};
		try { manifest = JSON.parse(DANCE_MANIFEST_JSON); } catch (e) {
			this.logService.error('[dance] failed to parse manifest', e as Error);
			// eslint-disable-next-line no-console
			console.error('[dance] failed to parse manifest', e);
		}

		const shim = this.shim;
		(shim as any).__danceManifest = manifest;

		const moduleObj = { exports: {} as any };
		const requireFn = (id: string): any => {
			if (id === 'vscode') { return shim; }
			throw new Error(`[dance] in-renderer mode does not provide module: ${id}`);
		};

		try {
			// `keep-names` is on in dance's esbuild output, so error stacks stay readable.
			const fn = new Function('module', 'exports', 'require', '__filename', '__dirname', DANCE_BUNDLE_JS);
			fn(moduleObj, moduleObj.exports, requireFn, '/dance/extension.js', '/dance');
			this._exports = moduleObj.exports;
			// eslint-disable-next-line no-console
			console.info('[dance] bundle eval ok; exports keys=' + Object.keys(this._exports ?? {}).join(','));
		} catch (e) {
			this.logService.error('[dance] bundle failed to load', e as Error);
			// eslint-disable-next-line no-console
			console.error('[dance] bundle failed to load', e);
			return;
		}

		const subscriptions: any[] = [];
		const ctx = {
			subscriptions,
			extensionPath: '/dance',
			extensionUri: URI.parse('memory:/dance'),
			environmentVariableCollection: { persistent: false, replace() { }, append() { }, prepend() { }, get() { return undefined; }, forEach() { }, delete() { }, clear() { } },
			storagePath: undefined,
			globalStoragePath: undefined,
			logPath: undefined,
			extensionMode: 1, // ExtensionMode.Production
			storageUri: undefined,
			globalStorageUri: undefined,
			logUri: undefined,
			workspaceState: { keys: () => [], get: () => undefined, update: () => Promise.resolve() },
			globalState: { keys: () => [], get: () => undefined, update: () => Promise.resolve(), setKeysForSync: () => undefined },
			secrets: { get: () => Promise.resolve(undefined), store: () => Promise.resolve(), delete: () => Promise.resolve(), onDidChange: () => ({ dispose() { } }) },
			asAbsolutePath: (p: string) => `/dance/${p}`,
			extension: { id: 'gregoire.dance', extensionUri: URI.parse('memory:/dance'), packageJSON: manifest, isActive: true, exports: undefined },
		};

		try {
			if (typeof this._exports?.activate === 'function') {
				// eslint-disable-next-line no-console
				console.info('[dance] calling dance.activate(ctx) …');
				const res = await Promise.resolve(this._exports.activate(ctx));
				(ctx.extension as any).exports = res;
				this.logService.info('[dance] activated in renderer main thread');
				// eslint-disable-next-line no-console
				console.info('[dance] activate() returned; subscriptions=' + subscriptions.length);
			} else {
				// eslint-disable-next-line no-console
				console.warn('[dance] exports.activate is not a function — typeof=' + typeof this._exports?.activate);
			}
		} catch (e) {
			this.logService.error('[dance] activate() threw', e as Error);
			// eslint-disable-next-line no-console
			console.error('[dance] activate() threw', e);
		}

		// Track any disposables the extension push'd to ctx.subscriptions and dispose them
		// when the contribution itself dies.
		this.ownDisposables.add({
			dispose() {
				for (const s of subscriptions) {
					try { s?.dispose?.(); } catch { /* ignore */ }
				}
			}
		});
	}

	override dispose(): void {
		try { this._exports?.deactivate?.(); } catch { /* ignore */ }
		super.dispose();
	}
}

export type { IVscodeShim };
